# Generated by Django 5.1 on 2024-08-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='courses',
            field=models.ManyToManyField(related_name='enrollments', through='courses.SubscriptionCourse', to='courses.course'),
        ),
    ]
