# Generated by Django 5.1 on 2024-08-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_subscription_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioncourse',
            name='completed_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
